### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by davidhesselbom** [vidhance/vidhance.com#17]
Currently, we have a contact form on a separate page, as well as a contact section on the "about" page. On the "about" page, there's is an e-mail address: info@imint.se. Do we really need both a contact form and an e-mail address?

Also, the address is info@imint.se. Should it be info@vidhance.com?

**Comment by jonathanudd** [comment]
The contact part of the about page is now removed. The email address is also changed to infot@vidhance.com.
