### ISSUE TITLE
Mixed languages

### ISSUE THREAD

**Issue by davidhesselbom** [vidhance/vidhance.com#2]
On https://github.com/vidhance/vidhance.com/blob/master/content/careers/ads/juniorEngineer.md, some  ~~titles~~ headings are still in English, e.g. "Job definition", "Qualifications"...

**Comment by simonmika** [comment]
As we require working knowledge in Swedish for employment the finer 
details they can contain the information in Swedish. Writting add copy 
in Swedish creates a selection by itself.

/Simon

Den 2015-07-16 13:57, David Hesselbom skrev:

**Comment by davidhesselbom** [comment]
My issue isn't that the document is written in Swedish, but that some ~~titles~~ headings are left untranslated and are still in English, so you have both "Att jobba hos oss", "Ytterligare meriter", "Job definition" and "Qualifications" in the same document.
